name: Deployment

on:
  push:
    branches: [main]
    
jobs:
  build:
    runs-on: ubuntu-latest
    
     steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Setup Node.js environment
      uses: actions/setup-node@v2-beta
      with: 
        version: 12
        
    - name: GitHub Action for Yarn
      uses: Borales/actions-yarn@v2.1.0
      with:
        # Yarn command
        cmd: install # npm install/ yarn install
    
    - name: Creating build
      run: CI=false yarn build
    
    - name: installing surge  
      run: npm install -g surge
    
    - name: deploying on surge
      run: surge ./build tiny-short-animation-by-asadullahkhan.surge.sh --token ${{secrets.SURGE_TOKEN}}
